(* ================================================================== *)
(*  theories/S1/Witness_PencilDet.v                                     *)
(*                                                                      *)
(*  Autogenerated by python/build_pencil_determinants.py.               *)
(*                                                                      *)
(*  Integer determinant numeral used by CertPencil.v:                   *)
(*                                                                      *)
(*    det_M1_int_value   = det(M1_int)            (positive)            *)
(*                                                                      *)
(*  CertPencil.v's `det_M1_int_pos` reduces to checking this literal's *)
(*  sign by `vm_compute`, after a CRT-style cross-check tying the       *)
(*  shipped value to `List.nth 0 (char_poly_int M1_int) 0`.             *)
(*                                                                      *)
(*  The pencil determinant `D_pencil_int_value` is shipped by           *)
(*  Witness_PencilClean.v (as an alias of `D_pencil_clean_value`), the *)
(*  CLEAN integer pencil's determinant — 2613 bits instead of 31131.   *)
(* ================================================================== *)

From Stdlib Require Import ZArith.
Open Scope Z_scope.

(* det(M1_int): 2044 bits, positive *)
Definition det_M1_int_value : Z := (1489957334573443112889775507832639350100585108413140128535147832875394785931983264421806699132116706105736588695096730872545116810777387799517556576378623428981524701012207946386669366939374963907931737465768102668962023244175710025221361659509045366791756013518231574593581386268458644778707307410019828658600945741743962948865144852517686523875163487234558994158454203434123092339706623760502695652961617580593751620832810713112664999248079773214564531893343455556813298778901281602958981231138678946077794864932550047851752361696075326261546993567019825377428787760436534881591796875000000000000000000000000000000)%Z.
