(* ============================================================== *)
(* AUTOGENERATED by python/build_quad_witness.py — do not edit.   *)
(* Maynard `M_{105} > 4` Rayleigh-quotient witness vector.        *)
(*                                                                  *)
(* The pair (M1_int, M2_int) is shipped by theories/S1/Witness.v.   *)
(* This file ships a rational vector v in Q^42 such that             *)
(*    105 * v^T M2 v  >  4 * v^T M1 v       and   v^T M1 v > 0,      *)
(* both inequalities verifiable by a single exact integer compare.   *)
(*                                                                  *)
(* Provenance:                                                      *)
(*   - top right eigenvector of M1^{-1} M2 from acb_mat.eig at     *)
(*     1024-bit precision, phase-aligned (largest entry positive real)*)
(*   - Mathematica-style absolute-tolerance Rationalize with         *)
(*     tol = 10^-14 (continued-fraction convergents).         *)
(*                                                                  *)
(* Verification statistics (all exact over Q):                      *)
(*   non-zero entries          = 42 / 42                          *)
(*   max v_i.denominator       = 67213321643309            *)
(*                              (~13.8 dec digits, 46 bits)              *)
(*   v^T M1 v > 0              : verified                            *)
(*   slack  = (105*v^T M2 v - 4*v^T M1 v) / v^T M1 v                *)
(*          ≈ +2.069761e-03                                          *)
(*                                                                  *)
(* The 42 entries are listed in the same row/column order as the    *)
(* MaynardBasis.maynard_basis enumeration (pinned by                 *)
(* maynard_basis_eq_witness in Witness.v).                           *)
(*                                                                  *)
(* Note: the eigenvector spans ~14 decimal orders of magnitude       *)
(* (smallest non-zero |v_i| ≈ 1e-14 vs. largest ≈ 1), which lower-    *)
(* bounds the denominator size.  This matches the ill-conditioning   *)
(* of M1; truncating small components destroys the inequality.       *)
(* ============================================================== *)

From Stdlib Require Import ZArith List.
Import ListNotations.
Open Scope Z_scope.

(* v_witness[i] = (num_i, den_i), with gcd(|num_i|, den_i) = 1 and den_i > 0. *)
Definition v_witness : list (Z * Z) :=
  [
  ((-1)%Z, 67213321643309%Z) ;
  ((-1)%Z, 127608469198%Z) ;
  (1%Z, 279653882552%Z) ;
  ((-1)%Z, 12020445731%Z) ;
  (1%Z, 549859441%Z) ;
  ((-1)%Z, 1793413588%Z) ;
  ((-1)%Z, 2852111653%Z) ;
  (1%Z, 39510722%Z) ;
  (3%Z, 12111503%Z) ;
  ((-1)%Z, 5889766%Z) ;
  ((-1)%Z, 3065036%Z) ;
  ((-11)%Z, 16762960%Z) ;
  (1%Z, 56351289%Z) ;
  ((-4)%Z, 1502055%Z) ;
  ((-368)%Z, 7848717%Z) ;
  ((-248)%Z, 7629181%Z) ;
  (83%Z, 10305760%Z) ;
  (874%Z, 12663047%Z) ;
  (2999%Z, 13498748%Z) ;
  (389%Z, 4466540%Z) ;
  ((-3)%Z, 6400234%Z) ;
  (1277%Z, 10688233%Z) ;
  (11484%Z, 3794749%Z) ;
  (39537%Z, 8813404%Z) ;
  (6952%Z, 10377483%Z) ;
  ((-6142)%Z, 31211377%Z) ;
  ((-227846)%Z, 52361791%Z) ;
  ((-150115)%Z, 7175034%Z) ;
  ((-250783)%Z, 22648711%Z) ;
  (37237%Z, 12498809%Z) ;
  (67%Z, 12886771%Z) ;
  ((-35583)%Z, 17941657%Z) ;
  ((-522509)%Z, 7595235%Z) ;
  ((-1507327)%Z, 7740852%Z) ;
  ((-365121)%Z, 2548910%Z) ;
  ((-499886)%Z, 13468967%Z) ;
  (14389%Z, 7143324%Z) ;
  (5289169%Z, 57282634%Z) ;
  (11505763%Z, 16419588%Z) ;
  (1%Z, 1%Z) ;
  (15488075%Z, 35377856%Z) ;
  (312214%Z, 4565683%Z)
  ].
