"""
Compute the two integer determinants needed by theories/S1/CertPencil.v:

  det_M1_int_value   := det(M1_int)
  D_pencil_int_value := det(4*D_M2*M1_int - 105*D_M1*M2_int)

Both are integer determinants of 42x42 matrices with bignum entries.
We use FLINT's fmpz_mat.det for the computation (exact, polynomial time).

Outputs Rocq Z literals appended to theories/S1/Witness_Quad.v (or a
sibling file).  Used by CertPencil.v to close `det_M1_int_pos` and
`D_pencil_int_neg`.

Run:  .venv/bin/python python/build_pencil_determinants.py
"""
from __future__ import annotations
import pickle, sys, time
from fractions import Fraction
from math import lcm
from pathlib import Path

sys.set_int_max_str_digits(100000)  # 31k-bit det = ~9400 digits

from flint import fmpz_mat, fmpz

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
CACHE = HERE / "m1m2.pkl"

print("Loading M1, M2 from m1m2.pkl ...", flush=True)
with open(CACHE, "rb") as f:
    M1_rat, M2_rat = pickle.load(f)

def common_denom(M):
    d = 1
    for row in M:
        for x in row:
            d = lcm(d, x.denominator)
    return d

def clear(M, D):
    return [[int(x * D) for x in row] for row in M]

print("Clearing denominators ...", flush=True)
D_M1 = common_denom(M1_rat)
D_M2 = common_denom(M2_rat)
M1_int = clear(M1_rat, D_M1)
M2_int = clear(M2_rat, D_M2)
print(f"  D_M1 bit-length = {D_M1.bit_length()}", flush=True)
print(f"  D_M2 bit-length = {D_M2.bit_length()}", flush=True)

# === det(M1_int) ===
print("Computing det(M1_int) ...", flush=True)
t0 = time.time()
M1_fmpz = fmpz_mat([[fmpz(x) for x in row] for row in M1_int])
det_M1 = int(M1_fmpz.det())
print(f"  done in {time.time()-t0:.2f}s; bits = {det_M1.bit_length()}; sign = {'positive' if det_M1 > 0 else ('zero' if det_M1 == 0 else 'negative')}", flush=True)
assert det_M1 > 0, "M1 should be positive definite -> det positive"

# === pencil matrix P = 4*D_M2*M1_int - 105*D_M1*M2_int ===
print("Building pencil matrix P = 4*D_M2*M1_int - 105*D_M1*M2_int ...", flush=True)
P = [[4*D_M2*M1_int[i][j] - 105*D_M1*M2_int[i][j] for j in range(42)] for i in range(42)]
max_P_bits = max(abs(x).bit_length() for row in P for x in row)
print(f"  max entry bits = {max_P_bits}", flush=True)

print("Computing det(P) ...", flush=True)
t0 = time.time()
P_fmpz = fmpz_mat([[fmpz(x) for x in row] for row in P])
det_P = int(P_fmpz.det())
print(f"  done in {time.time()-t0:.2f}s; bits = {abs(det_P).bit_length()}; sign = {'positive' if det_P > 0 else ('zero' if det_P == 0 else 'negative')}", flush=True)
assert det_P < 0, ("expected det(P) < 0 (witnesses an eigenvalue of M1^{-1}M2 > 4/105);"
                  " got det_P = " + str(det_P))

# === Emit Rocq source ===
OUT = ROOT / "theories" / "S1" / "Witness_PencilDet.v"
print(f"Writing {OUT} ...", flush=True)

def z_lit(n):
    # Rocq Z literal for n.  Use the standard Stdlib BinNums encoding,
    # which the parser handles for both positive and negative.
    return f"({n})%Z"

with open(OUT, "w") as f:
    f.write("(* ================================================================== *)\n")
    f.write("(*  theories/S1/Witness_PencilDet.v                                     *)\n")
    f.write("(*                                                                      *)\n")
    f.write("(*  Autogenerated by python/build_pencil_determinants.py.               *)\n")
    f.write("(*                                                                      *)\n")
    f.write("(*  Two integer-determinant numerals used by CertPencil.v:              *)\n")
    f.write("(*                                                                      *)\n")
    f.write("(*    det_M1_int_value   = det(M1_int)            (positive)            *)\n")
    f.write("(*    D_pencil_int_value = det(4*D_M2*M1_int -                          *)\n")
    f.write("(*                              105*D_M1*M2_int)  (negative)            *)\n")
    f.write("(*                                                                      *)\n")
    f.write("(*  CertPencil.v's `det_M1_int_pos` and `D_pencil_int_neg` reduce       *)\n")
    f.write("(*  to checking these literals' signs by `vm_compute`, after a          *)\n")
    f.write("(*  CRT-style cross-check tying the shipped values to                   *)\n")
    f.write("(*  `List.nth 0 (char_poly_int <matrix>) 0`.                            *)\n")
    f.write("(* ================================================================== *)\n\n")
    f.write("From Stdlib Require Import ZArith.\n")
    f.write("Open Scope Z_scope.\n\n")
    f.write(f"(* det(M1_int): {det_M1.bit_length()} bits, positive *)\n")
    f.write(f"Definition det_M1_int_value : Z := {z_lit(det_M1)}.\n\n")
    f.write(f"(* det(4*D_M2*M1_int - 105*D_M1*M2_int): {abs(det_P).bit_length()} bits, negative *)\n")
    f.write(f"Definition D_pencil_int_value : Z := {z_lit(det_P)}.\n")

print(f"  det_M1_int_value: {det_M1.bit_length()} bits", flush=True)
print(f"  D_pencil_int_value: {abs(det_P).bit_length()} bits", flush=True)
print("Done.", flush=True)
