"""
[QUAD-BRANCH NOTE]  Since the clean-pencil refactor, the pencil
determinant `D_pencil_int_value` is generated by
`build_pencil_clean.py` (which ships the CLEAN integer pencil — 2613
bits instead of 31131).  This script now only emits the M1
determinant.

If you re-run this script, only `det_M1_int_value` will be regenerated
in `theories/S1/Witness_PencilDet.v`.  The `D_pencil_int_value` alias
lives in `theories/S1/Witness_PencilClean.v`.

Compute det(M1_int) for theories/S1/CertPencil.v.  Integer det of a
42x42 bignum matrix via FLINT's fmpz_mat.det (exact, polynomial time).

Run:  .venv/bin/python python/build_pencil_determinants.py
"""
from __future__ import annotations
import pickle, sys, time
from fractions import Fraction
from math import lcm
from pathlib import Path

sys.set_int_max_str_digits(100000)  # 31k-bit det = ~9400 digits

from flint import fmpz_mat, fmpz

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
CACHE = HERE / "m1m2.pkl"

print("Loading M1, M2 from m1m2.pkl ...", flush=True)
with open(CACHE, "rb") as f:
    M1_rat, M2_rat = pickle.load(f)

def common_denom(M):
    d = 1
    for row in M:
        for x in row:
            d = lcm(d, x.denominator)
    return d

def clear(M, D):
    return [[int(x * D) for x in row] for row in M]

print("Clearing denominators ...", flush=True)
D_M1 = common_denom(M1_rat)
D_M2 = common_denom(M2_rat)
M1_int = clear(M1_rat, D_M1)
M2_int = clear(M2_rat, D_M2)
print(f"  D_M1 bit-length = {D_M1.bit_length()}", flush=True)
print(f"  D_M2 bit-length = {D_M2.bit_length()}", flush=True)

# === det(M1_int) ===
print("Computing det(M1_int) ...", flush=True)
t0 = time.time()
M1_fmpz = fmpz_mat([[fmpz(x) for x in row] for row in M1_int])
det_M1 = int(M1_fmpz.det())
print(f"  done in {time.time()-t0:.2f}s; bits = {det_M1.bit_length()}; sign = {'positive' if det_M1 > 0 else ('zero' if det_M1 == 0 else 'negative')}", flush=True)
assert det_M1 > 0, "M1 should be positive definite -> det positive"

# === Emit Rocq source ===
OUT = ROOT / "theories" / "S1" / "Witness_PencilDet.v"
print(f"Writing {OUT} ...", flush=True)

def z_lit(n):
    # Rocq Z literal for n.  Use the standard Stdlib BinNums encoding,
    # which the parser handles for both positive and negative.
    return f"({n})%Z"

with open(OUT, "w") as f:
    f.write("(* ================================================================== *)\n")
    f.write("(*  theories/S1/Witness_PencilDet.v                                     *)\n")
    f.write("(*                                                                      *)\n")
    f.write("(*  Autogenerated by python/build_pencil_determinants.py.               *)\n")
    f.write("(*                                                                      *)\n")
    f.write("(*  Integer determinant numeral used by CertPencil.v:                   *)\n")
    f.write("(*                                                                      *)\n")
    f.write("(*    det_M1_int_value   = det(M1_int)            (positive)            *)\n")
    f.write("(*                                                                      *)\n")
    f.write("(*  CertPencil.v's `det_M1_int_pos` reduces to checking this literal's *)\n")
    f.write("(*  sign by `vm_compute`, after a CRT-style cross-check tying the       *)\n")
    f.write("(*  shipped value to `List.nth 0 (char_poly_int M1_int) 0`.             *)\n")
    f.write("(*                                                                      *)\n")
    f.write("(*  The pencil determinant `D_pencil_int_value` is shipped by           *)\n")
    f.write("(*  Witness_PencilClean.v (as an alias of `D_pencil_clean_value`), the *)\n")
    f.write("(*  CLEAN integer pencil's determinant — 2613 bits instead of 31131.   *)\n")
    f.write("(* ================================================================== *)\n\n")
    f.write("From Stdlib Require Import ZArith.\n")
    f.write("Open Scope Z_scope.\n\n")
    f.write(f"(* det(M1_int): {det_M1.bit_length()} bits, positive *)\n")
    f.write(f"Definition det_M1_int_value : Z := {z_lit(det_M1)}.\n")

print(f"  det_M1_int_value: {det_M1.bit_length()} bits", flush=True)
print("Done.", flush=True)
