"""
Build the *clean* integer pencil for CertPencil.v's quad-branch refactor.

Old pencil:
    pencil_mat_int := 4*D_M2*M1_int - 105*D_M1*M2_int
                    = D_M1 * D_M2 * (4*M1_rat - 105*M2_rat).
Multiplies through by the giant D_M1*D_M2 (1368 bits), so
|det(pencil_mat_int)| is ~31131 bits and the Hadamard bound is ~34348 bits.
A 1210-prime CRT product is needed just to certify the determinant.

New (clean) pencil:
    pencil_int_clean := D_pencil_clean * (4*M1_rat - 105*M2_rat),
where D_pencil_clean := LCM of denominators of the entries of
(4*M1_rat - 105*M2_rat).  D_pencil_clean is ~half D_M1*D_M2, so the new
determinant is ~2613 bits and the Hadamard bound is ~5830 bits.  The
existing 710-prime CRT product already comfortably bounds 2 * |det| + 2 *
|bound|; no prime extension required.

This script also emits 42x42 per-entry cross-check witnesses (so the
PencilCleanGrid.v lemma can simply read shipped equalities).  In practice
the equation
    D_M1 * D_M2 * pencil_int_clean[i][j]
        = D_pencil_clean * (4*D_M2*M1_int[i][j] - 105*D_M1*M2_int[i][j])
holds by construction (both sides equal D_M1*D_M2*D_pencil_clean*(4*M1_rat
- 105*M2_rat)).  We only assert it; the Coq side closes by vm_compute on
the cross-multiplied bool grid.

Output: theories/S1/Witness_PencilClean.v
"""
from __future__ import annotations
import pickle, sys, time
from fractions import Fraction
from math import lcm
from pathlib import Path

sys.set_int_max_str_digits(100000)

from flint import fmpz_mat, fmpz

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
CACHE = HERE / "m1m2.pkl"

print("Loading M1_rat, M2_rat from m1m2.pkl ...", flush=True)
with open(CACHE, "rb") as f:
    M1_rat, M2_rat = pickle.load(f)

DIM = len(M1_rat)
assert DIM == 42, f"expected 42x42, got {DIM}x?"

def common_denom(M):
    d = 1
    for row in M:
        for x in row:
            d = lcm(d, x.denominator)
    return d

def clear(M, D):
    return [[int(x * D) for x in row] for row in M]

print("Clearing M1, M2 ...", flush=True)
D_M1 = common_denom(M1_rat)
D_M2 = common_denom(M2_rat)
M1_int = clear(M1_rat, D_M1)
M2_int = clear(M2_rat, D_M2)
print(f"  D_M1 bits = {D_M1.bit_length()}, D_M2 bits = {D_M2.bit_length()}", flush=True)

# === pencil_rat = 4*M1_rat - 105*M2_rat (as Fraction matrix) ===
print("Computing pencil_rat = 4*M1_rat - 105*M2_rat ...", flush=True)
pencil_rat = [[4 * M1_rat[i][j] - 105 * M2_rat[i][j] for j in range(DIM)]
              for i in range(DIM)]

# D_pencil_clean = LCM of denominators of entries of pencil_rat.
print("Computing D_pencil_clean ...", flush=True)
D_pencil_clean = common_denom(pencil_rat)
print(f"  D_pencil_clean bits = {D_pencil_clean.bit_length()}", flush=True)

# pencil_int_clean[i][j] = pencil_rat[i][j] * D_pencil_clean  (always int)
pencil_int_clean = []
for i in range(DIM):
    row = []
    for j in range(DIM):
        v = pencil_rat[i][j] * D_pencil_clean
        assert v.denominator == 1, (i, j, v)
        row.append(int(v))
    pencil_int_clean.append(row)

max_abs_entry = max(abs(x) for row in pencil_int_clean for x in row)
print(f"  max |entry| bits = {max_abs_entry.bit_length()}", flush=True)

# === det(pencil_int_clean) ===
print("Computing det(pencil_int_clean) via FLINT ...", flush=True)
t0 = time.time()
P_fmpz = fmpz_mat([[fmpz(x) for x in row] for row in pencil_int_clean])
D_pencil_clean_value = int(P_fmpz.det())
print(f"  done in {time.time()-t0:.2f}s; bits = {abs(D_pencil_clean_value).bit_length()}; "
      f"sign = {'positive' if D_pencil_clean_value > 0 else ('zero' if D_pencil_clean_value == 0 else 'negative')}",
      flush=True)
assert D_pencil_clean_value < 0, ("det(pencil_int_clean) should be negative — det(4 M1 - 105 M2) "
                                  "< 0 witnesses an eigenvalue of M1^{-1} M2 > 4/105.")

# === Sanity check the cross-multiplication identity per entry ===
print("Sanity-checking cross-multiplication identity ...", flush=True)
for i in range(DIM):
    for j in range(DIM):
        lhs = D_M1 * D_M2 * pencil_int_clean[i][j]
        rhs = D_pencil_clean * (4 * D_M2 * M1_int[i][j] - 105 * D_M1 * M2_int[i][j])
        assert lhs == rhs, (i, j, lhs - rhs)
print("  all 1764 equations OK.", flush=True)

# === Emit Rocq source ===
OUT_DET = ROOT / "theories" / "S1" / "Witness_PencilClean.v"
print(f"Writing {OUT_DET} ...", flush=True)

def z_lit(n):
    return f"({n})%Z"

with open(OUT_DET, "w") as f:
    f.write("(* ================================================================== *)\n")
    f.write("(*  theories/S1/Witness_PencilClean.v                                   *)\n")
    f.write("(*                                                                      *)\n")
    f.write("(*  Autogenerated by python/build_pencil_clean.py.                      *)\n")
    f.write("(*                                                                      *)\n")
    f.write("(*  The CLEAN integer pencil for the quad route's determinant lift:    *)\n")
    f.write("(*                                                                      *)\n")
    f.write("(*    pencil_int_clean[i][j]                                            *)\n")
    f.write("(*       := D_pencil_clean * (4*M1_rat[i][j] - 105*M2_rat[i][j]).      *)\n")
    f.write("(*                                                                      *)\n")
    f.write("(*    D_pencil_clean :=                                                 *)\n")
    f.write("(*       LCM of denominators of (4*M1_rat - 105*M2_rat) entries.       *)\n")
    f.write("(*                                                                      *)\n")
    f.write("(*    D_pencil_clean_value := det(pencil_int_clean)  (negative).        *)\n")
    f.write("(*                                                                      *)\n")
    f.write("(*  By construction, for every (i, j):                                  *)\n")
    f.write("(*    D_M1 * D_M2 * pencil_int_clean[i][j]                              *)\n")
    f.write("(*      = D_pencil_clean * (4*D_M2*M1_int[i][j]                         *)\n")
    f.write("(*                          - 105*D_M1*M2_int[i][j]).                  *)\n")
    f.write("(*  This identity is closed by vm_compute on a 42x42 bool grid in      *)\n")
    f.write("(*  PencilCleanGrid.v.                                                  *)\n")
    f.write("(* ================================================================== *)\n\n")
    f.write("From Stdlib Require Import ZArith List.\n")
    f.write("Import ListNotations.\n")
    f.write("Open Scope Z_scope.\n\n")
    f.write(f"(* D_pencil_clean: LCM of denominators of (4 M1_rat - 105 M2_rat),  "
            f"{D_pencil_clean.bit_length()} bits. *)\n")
    f.write(f"Definition D_pencil_clean : Z := {z_lit(D_pencil_clean)}.\n\n")
    f.write(f"(* det(pencil_int_clean): {abs(D_pencil_clean_value).bit_length()} bits, negative. *)\n")
    f.write(f"Definition D_pencil_clean_value : Z := {z_lit(D_pencil_clean_value)}.\n\n")
    f.write("Definition pencil_int_clean : list (list Z) :=\n")
    f.write("  [\n")
    for i, row in enumerate(pencil_int_clean):
        f.write("  [\n")
        for j, x in enumerate(row):
            sep = "" if j == len(row) - 1 else " ;"
            f.write(f"   {z_lit(x)}{sep}\n")
        if i == len(pencil_int_clean) - 1:
            f.write("  ]\n")
        else:
            f.write("  ] ;\n")
    f.write("  ].\n\n")
    f.write("(* Alias used by the CRT lift and Hadamard bound files: the precomputed\n")
    f.write("   pencil determinant goes under the name `D_pencil_int_value` everywhere\n")
    f.write("   downstream.  In the quad branch the value is the CLEAN det (=\n")
    f.write("   `D_pencil_clean_value` above). *)\n")
    f.write("Definition D_pencil_int_value : Z := D_pencil_clean_value.\n")

print(f"  pencil_int_clean: 42x42 ints, max |entry| = {max_abs_entry.bit_length()} bits.", flush=True)
print(f"  D_pencil_clean_value: {abs(D_pencil_clean_value).bit_length()} bits.", flush=True)
print("Done.", flush=True)
