"""
Convert certificate.json (and optionally certificate_chain.json) into
Rocq source files under theories/S1/.

Outputs:
  theories/S1/Witness.v        — small (~200 KB): M1_int, M2_int, charpoly,
                                  signs, V counts.
  theories/S1/WitnessChain.v   — heavy (~12 MB): the Brown–Traub PRS chain
                                  and the β coefficients. Only emitted if
                                  --with-chain is passed.

Usage:
  python tools/json_to_v.py                  # only Witness.v
  python tools/json_to_v.py --with-chain     # also WitnessChain.v
"""
from __future__ import annotations
import argparse, json, sys, textwrap
from pathlib import Path

# Big integer literals require Python's int_max_str_digits to be raised.
sys.set_int_max_str_digits(1_000_000)

ROOT = Path(__file__).resolve().parent.parent
CERT      = ROOT / "certificate.json"
CERT_HEAVY = ROOT / "certificate_chain.json"
OUT_DIR   = ROOT / "theories" / "S1"
OUT_DIR.mkdir(parents=True, exist_ok=True)

# ----------------------------------------------------------------------
# Rocq emission helpers.
# ----------------------------------------------------------------------
#
# Stdlib `Z` literals over ~10 000 bits stack-overflow `coqc`. We use them
# only for small values (Witness.v: 1354-bit max).  For the giant Sturm
# chain literals (up to ~200 000 bits), we switch to `rocq-bignums`'s `bigZ`
# whose number notation handles 100 kbit literals in ~0.4 s each. The
# bridge to stdlib Z is `BigZ.to_Z` (see Recompose.v).

def z_lit(n: int | str) -> str:
    """Render an integer as a stdlib `Z` literal: `12345%Z`, `(-7)%Z`."""
    n = int(n)
    return f"({n})%Z" if n < 0 else f"{n}%Z"

def bigz_lit(n: int | str) -> str:
    """Render an integer as a `bigZ` literal: `12345%bigZ`, `(-7)%bigZ`."""
    n = int(n)
    return f"({n})%bigZ" if n < 0 else f"{n}%bigZ"

def list_z(xs):
    """Render a list of small `Z` values as `[a%Z; b%Z; c%Z]`. Use only
    for values guaranteed to fit in ~5 kbits."""
    xs = list(xs)
    if not xs:
        return "(@nil Z)"
    inner = " ;\n   ".join(z_lit(x) for x in xs)
    return f"[\n   {inner}\n  ]"

def list_list_z(rows):
    inner = " ;\n  ".join(list_z(row) for row in rows)
    return f"[\n  {inner}\n  ]"

def list_bigz(xs):
    """Render a list of (potentially huge) integers as `[a%bigZ; b%bigZ; ...]`."""
    xs = list(xs)
    if not xs:
        return "(@nil BigZ.t_)"
    inner = " ;\n   ".join(bigz_lit(x) for x in xs)
    return f"[\n   {inner}\n  ]"

def list_list_bigz(rows):
    inner = " ;\n  ".join(list_bigz(row) for row in rows)
    return f"[\n  {inner}\n  ]"

def emit_definition(name: str, ty: str, body: str) -> str:
    return f"Definition {name} : {ty} :=\n  {body}.\n"

# ----------------------------------------------------------------------
# Witness.v (small).
# ----------------------------------------------------------------------
def emit_witness(meta: dict) -> str:
    out = []
    out.append(textwrap.dedent("""\
        (* ============================================================== *)
        (* AUTOGENERATED by tools/json_to_v.py — do not edit by hand.     *)
        (* Source: certificate.json from python/build_certificate.py.     *)
        (* Maynard `M_{105} > 4` certificate, integer-cleared.             *)
        (* ============================================================== *)

        From Stdlib Require Import ZArith List.
        Import ListNotations.
        Open Scope Z_scope.

    """))

    out.append(f"Definition dim : nat := {meta['dim']}.\n")
    out.append(f"Definition k_param : nat := {meta['k']}.\n")
    out.append(f"Definition deg_max : nat := {meta['deg_max']}.\n\n")

    # Threshold 4/105 as a pair (numerator, denominator).
    th = meta["threshold_x0"]
    out.append(f"Definition threshold_num : Z := {z_lit(th['num'])}.\n")
    out.append(f"Definition threshold_den : Z := {z_lit(th['den'])}.\n\n")

    # The basis (list of (b, c)).
    basis_pairs = " ;\n      ".join(
        f"({a}%nat, {b}%nat)" for a, b in meta["basis"]
    )
    out.append(textwrap.dedent(f"""\
        (* The 42 basis monomials (b, c) with b + 2c <= 11. *)
        Definition basis : list (nat * nat) :=
          [
            {basis_pairs}
          ].

    """))

    # M1 and M2 as integer-cleared matrices.
    out.append("(* M1[i,j] = M1_int[i][j] / D_M1.  Symmetric, positive definite over Q. *)\n")
    out.append(f"Definition D_M1 : Z := {z_lit(meta['D_M1'])}.\n\n")
    out.append(emit_definition("M1_int", "list (list Z)", list_list_z(meta["M1_int"])))
    out.append("\n")

    out.append("(* M2[i,j] = M2_int[i][j] / D_M2.  Symmetric. *)\n")
    out.append(f"Definition D_M2 : Z := {z_lit(meta['D_M2'])}.\n\n")
    out.append(emit_definition("M2_int", "list (list Z)", list_list_z(meta["M2_int"])))
    out.append("\n")

    # Characteristic polynomial of A = M1^{-1} M2.
    cp = meta["charpoly"]
    out.append(textwrap.dedent(f"""\
        (* Characteristic polynomial of A = M1^{{-1}} M2.
           q(x) ∈ Q[x], degree {cp['deg']}; we ship the integer-cleared
           polynomial Q(x) = D_q * q(x) ∈ Z[x], coefficients low-to-high.    *)
        Definition D_q : Z := {z_lit(cp['common_den'])}.

    """))
    out.append(emit_definition(
        "charpoly_int",
        "list Z",
        list_z(cp["coefs_low_to_high"]),
    ))
    out.append("\n")

    # Signs and V counts.
    out.append(f"Definition signs_at_x0  : list Z := {list_z(meta['signs_at_x0'])}.\n\n")
    out.append(f"Definition signs_at_inf : list Z := {list_z(meta['signs_at_inf'])}.\n\n")
    out.append(f"Definition V_x0  : nat := {meta['V_x0']}%nat.\n")
    out.append(f"Definition V_inf : nat := {meta['V_inf']}%nat.\n")
    out.append(f"Definition roots_in_x0_inf : nat := {meta['roots_in_x0_inf']}%nat.\n\n")

    # Cross-check value, as a comment only.
    out.append(textwrap.dedent(f"""\
        (* Independent Arb 256-bit cross-check (advisory; not part of the proof):
             top eigenvalue of A          = {meta['arb_top_eig']}
             k * top                      = {meta['arb_k_times_top']}
             matches Mathematica's value  4.00206976193804713…  to 12+ digits *)
    """))
    return "".join(out)

# ----------------------------------------------------------------------
# WitnessChain.v (heavy).
# ----------------------------------------------------------------------
def emit_witness_chain(heavy: dict) -> str:
    out = []
    out.append(textwrap.dedent("""\
        (* ============================================================== *)
        (* AUTOGENERATED by tools/json_to_v.py --with-chain.              *)
        (* Brown-Traub subresultant PRS chain for the Maynard char poly.  *)
        (*                                                                  *)
        (* Implementation notes                                             *)
        (* --------------------                                             *)
        (* Stdlib Z literals stack-overflow `coqc` above ~10 000 bits.      *)
        (* The chain has individual coefficients up to ~200 000 bits, so    *)
        (* we ship the chain as `bigZ` (rocq-bignums), whose number         *)
        (* notation handles 100 kbit literals in ~0.4 s each.  Lift to      *)
        (* stdlib Z lazily via the `lift_bigZ` / `lift_bigZ2` helpers in    *)
        (* Recompose.v when interfacing with `Z`-based machinery.           *)
        (* ============================================================== *)

        From Stdlib Require Import ZArith List.
        From Bignums Require Import BigZ.
        Import ListNotations.
        From PrimeGapS1 Require Import Recompose.
        Open Scope bigZ_scope.

    """))

    chain_len = heavy["chain_len"]
    out.append(f"Definition sturm_chain_len : nat := {chain_len}%nat.\n\n")

    # Each chain entry as its own Definition; this keeps the file
    # incrementally elaborable and lets coqc cache.
    for entry in heavy["sturm_chain"]:
        i = entry["i"]
        coefs = entry["coefs_low_to_high"]
        out.append(f"(* chain[{i}], degree {entry['deg']}, {len(coefs)} coefs *)\n")
        out.append(emit_definition(
            f"chain_{i}",
            "list BigZ.t_",
            list_bigz(coefs),
        ))
        out.append("\n")

    # The full chain as a list of lists (referenced by name to avoid
    # giant inline literals here).
    chain_refs = " ::\n    ".join(f"chain_{i}" for i in range(chain_len))
    out.append("(* Full chain assembled from per-entry definitions. *)\n")
    out.append(f"Definition sturm_chain_bigZ : list (list BigZ.t_) :=\n    {chain_refs} :: nil.\n\n")

    # The β coefficients used in each PRS step.
    out.append("(* β_i for i = 1 .. chain_len - 1; one per step. *)\n")
    out.append(emit_definition(
        "sturm_betas_bigZ",
        "list BigZ.t_",
        list_bigz(heavy["betas"]),
    ))
    out.append("\n")

    # Lazy stdlib-Z views of the chain & betas.  vm_compute will reduce
    # these on demand; the conversion is O(n log n) per element.
    out.append(textwrap.dedent("""\
        (* Stdlib-Z views, computed lazily via vm_compute. *)
        Definition sturm_chain : list (list Z) := lift_bigZ2 sturm_chain_bigZ.
        Definition sturm_betas : list Z        := lift_bigZ  sturm_betas_bigZ.
    """))

    return "".join(out)

# ----------------------------------------------------------------------
# Main.
# ----------------------------------------------------------------------
def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--with-chain", action="store_true",
                    help="Also emit WitnessChain.v from certificate_chain.json")
    args = ap.parse_args()

    if not CERT.exists():
        sys.exit(f"Missing {CERT}; run python/build_certificate.py first.")
    meta = json.loads(CERT.read_text())

    witness_v = OUT_DIR / "Witness.v"
    witness_v.write_text(emit_witness(meta))
    print(f"Wrote {witness_v}  ({witness_v.stat().st_size:,} bytes)")

    if args.with_chain:
        if not CERT_HEAVY.exists():
            sys.exit(f"Missing {CERT_HEAVY}; run python/build_certificate.py first.")
        heavy = json.loads(CERT_HEAVY.read_text())
        chain_v = OUT_DIR / "WitnessChain.v"
        chain_v.write_text(emit_witness_chain(heavy))
        print(f"Wrote {chain_v}  ({chain_v.stat().st_size:,} bytes)")

if __name__ == "__main__":
    main()
